[
  {
    id: 1,
    name: 'Buddy',
    pet_type: 'Dog',
    age: 4,
    breed: 'Labrador Retriever Mix',
    sex: 'Male',
    coloration: 'Golden',
    weight: 65,
    is_sterilized: 'Yes',
    description:
      "Buddy is a bundle of joy! He's a friendly and energetic boy who loves to play fetch and go for long walks. He's great with kids and other dogs, but not a fan of cats. He's already house-trained and knows basic commands. Buddy is looking for an active family to call his own.",
    date_created: '2025-06-15T10:00:00Z',
    images: [],
  },
  {
    id: 2,
    name: 'Lucy',
    pet_type: 'Cat',
    age: 2,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'Black and White Tuxedo',
    weight: 9,
    is_sterilized: 'Yes',
    description:
      "Lucy is a sweet and gentle soul. She can be a little shy at first, but once she warms up, she's a total lovebug who will purr for hours. She enjoys quiet afternoons napping in a sunbeam and would do best in a calm household. She gets along well with other mellow cats.",
    date_created: '2025-05-20T14:30:00Z',
    images: [],
  },
  {
    id: 3,
    name: 'Max',
    pet_type: 'Dog',
    age: 6,
    breed: 'German Shepherd',
    sex: 'Male',
    coloration: 'Black and Tan',
    weight: 80,
    is_sterilized: 'Yes',
    description:
      "Max is a loyal and intelligent companion. He's very well-trained and eager to please. He would excel with an experienced owner who can continue his training and provide him with plenty of mental stimulation. He's protective of his family and would make a fantastic watchdog.",
    date_created: '2025-07-01T09:00:00Z',
    images: [],
  },
  {
    id: 4,
    name: 'Daisy',
    pet_type: 'Dog',
    age: 1,
    breed: 'Beagle',
    sex: 'Female',
    coloration: 'Tricolor',
    weight: 22,
    is_sterilized: 'Yes',
    description:
      "Daisy is a happy-go-lucky puppy with a nose for adventure! She's curious, playful, and loves to follow scents. She's working on her leash manners but is a quick learner. She would love a home with a fenced yard where she can safely explore.",
    date_created: '2025-06-28T11:00:00Z',
    images: [],
  },
  {
    id: 5,
    name: 'Oliver',
    pet_type: 'Cat',
    age: 3,
    breed: 'Siamese Mix',
    sex: 'Male',
    coloration: 'Cream with Chocolate Points',
    weight: 11,
    is_sterilized: 'Yes',
    description:
      "Oliver is a vocal and affectionate cat who loves to be the center of attention. He'll greet you at the door with his charming meows and follow you around the house. He's very social and would do well in a home where he gets lots of interaction.",
    date_created: '2025-06-10T16:00:00Z',
    images: [],
  },
  {
    id: 6,
    name: 'Rocky',
    pet_type: 'Dog',
    age: 5,
    breed: 'Boxer Mix',
    sex: 'Male',
    coloration: 'Brindle',
    weight: 70,
    is_sterilized: 'Yes',
    description:
      "Rocky is a big goofball with a heart of gold. He has a playful, bouncy personality and loves everyone he meets. He would benefit from an owner who can handle his strength and continue his obedience training. He thinks he's a lap dog!",
    date_created: '2025-04-18T13:20:00Z',
    images: [],
  },
  {
    id: 7,
    name: 'Luna',
    pet_type: 'Cat',
    age: 1,
    breed: 'Maine Coon',
    sex: 'Female',
    coloration: 'Grey Tabby',
    weight: 12,
    is_sterilized: 'Yes',
    description:
      "Luna is a gentle giant with a magnificent fluffy coat. She's incredibly sweet-natured, playful, and gets along well with children and other pets. She loves to chase laser pointers and enjoys a good brushing session.",
    date_created: '2025-06-25T18:00:00Z',
    images: [],
  },
  {
    id: 8,
    name: 'Charlie',
    pet_type: 'Dog',
    age: 8,
    breed: 'Golden Retriever',
    sex: 'Male',
    coloration: 'Cream',
    weight: 75,
    is_sterilized: 'Yes',
    description:
      "Charlie is a distinguished senior gentleman looking for a comfortable home to spend his golden years. He's calm, gentle, and perfectly house-trained. His favorite activities include napping, short walks, and getting gentle scratches behind the ears.",
    date_created: '2025-03-30T12:00:00Z',
    images: [],
  },
  {
    id: 9,
    name: 'Milo',
    pet_type: 'Cat',
    age: 5,
    breed: 'Domestic Shorthair',
    sex: 'Male',
    coloration: 'Orange Tabby',
    weight: 13,
    is_sterilized: 'Yes',
    description:
      "Milo is a confident and friendly cat with a big personality. He loves to explore, play with toys, and will happily curl up on your lap for a nap. He's an easy-going companion who would fit into almost any home.",
    date_created: '2025-05-15T11:45:00Z',
    images: [],
  },
  {
    id: 10,
    name: 'Sadie',
    pet_type: 'Dog',
    age: 2,
    breed: 'Australian Shepherd Mix',
    sex: 'Female',
    coloration: 'Blue Merle',
    weight: 45,
    is_sterilized: 'Yes',
    description:
      'Sadie is a smart and energetic girl who needs a job to do! She would be a perfect partner for hiking, running, or agility training. She is very loving with her people but needs proper introductions to new dogs.',
    date_created: '2025-06-05T15:00:00Z',
    images: [],
  },
  {
    id: 11,
    name: 'Thumper',
    pet_type: 'Rabbit',
    age: 1,
    breed: 'Holland Lop',
    sex: 'Male',
    coloration: 'Grey and White',
    weight: 4,
    is_sterilized: 'Yes',
    description:
      'Thumper is an adorable, curious rabbit who loves to hop around and explore his surroundings. He is litter-box trained and enjoys munching on fresh hay and veggies. He would love a home where he can have plenty of safe space to roam.',
    date_created: '2025-06-22T10:30:00Z',
    images: [],
  },
  {
    id: 12,
    name: 'Zoe',
    pet_type: 'Dog',
    age: 3,
    breed: 'Poodle Mix (Doodle)',
    sex: 'Female',
    coloration: 'Apricot',
    weight: 30,
    is_sterilized: 'Yes',
    description:
      "Zoe is a hypoallergenic sweetheart who doesn't shed! She's playful, intelligent, and loves to cuddle. She's looking for a family who will include her in all their activities. She is great with kids and other pets.",
    date_created: '2025-02-14T17:00:00Z',
    images: [],
  },
  {
    id: 13,
    name: 'Simba',
    pet_type: 'Cat',
    age: 2,
    breed: 'Domestic Longhair',
    sex: 'Male',
    coloration: 'Ginger',
    weight: 10,
    is_sterilized: 'Yes',
    description:
      'With a mane as majestic as his namesake, Simba is a confident and regal cat. He enjoys being pampered and will reward you with loud purrs and headbutts. He prefers to be the only king of his castle (no other pets).',
    date_created: '2025-04-29T19:00:00Z',
    images: [],
  },
  {
    id: 14,
    name: 'Peanut',
    pet_type: 'Dog',
    age: 1,
    breed: 'Chihuahua Mix',
    sex: 'Male',
    coloration: 'Fawn',
    weight: 7,
    is_sterilized: 'Yes',
    description:
      "Peanut may be small, but he has a huge personality! He's a spunky and affectionate lap dog who loves to be carried around and doted on. He can be a bit yappy when excited but is a very loving companion.",
    date_created: '2025-06-19T14:00:00Z',
    images: [],
  },
  {
    id: 15,
    name: 'Willow',
    pet_type: 'Cat',
    age: 4,
    breed: 'Calico',
    sex: 'Female',
    coloration: 'Tricolor (White, Black, Orange)',
    weight: 8,
    is_sterilized: 'Yes',
    description:
      "Willow is a beautiful cat with a sassy and independent spirit. She likes affection on her own terms and will let you know when she wants to cuddle. She's a low-maintenance girl perfect for a patient owner.",
    date_created: '2025-03-11T16:30:00Z',
    images: [],
  },
  {
    id: 16,
    name: 'Gus',
    pet_type: 'Dog',
    age: 7,
    breed: 'Basset Hound',
    sex: 'Male',
    coloration: 'Brown and White',
    weight: 55,
    is_sterilized: 'Yes',
    description:
      "Gus is a laid-back, charming hound with the most soulful eyes. He enjoys leisurely strolls and long naps. He's a very easy-going and gentle dog who would make a wonderful companion for a relaxed family.",
    date_created: '2025-01-25T11:00:00Z',
    images: [],
  },
  {
    id: 17,
    name: 'Smokey',
    pet_type: 'Cat',
    age: 6,
    breed: 'Russian Blue',
    sex: 'Male',
    coloration: 'Solid Grey',
    weight: 12,
    is_sterilized: 'Yes',
    description:
      'Smokey is a handsome and reserved gentleman. He is very gentle and affectionate once he trusts you. He would prefer a quiet home without young children or loud noises. He loves bird-watching from a window perch.',
    date_created: '2025-05-02T13:00:00Z',
    images: [],
  },
  {
    id: 18,
    name: 'Ruby',
    pet_type: 'Dog',
    age: 3,
    breed: 'Pit Bull Terrier Mix',
    sex: 'Female',
    coloration: 'Red and White',
    weight: 50,
    is_sterilized: 'Yes',
    description:
      "Ruby is the sweetest girl you'll ever meet! She's a total people-lover who wants nothing more than to give kisses and cuddle on the couch. She is strong and energetic, so she needs an owner who can keep up with her.",
    date_created: '2024-12-10T10:00:00Z',
    images: [],
  },
  {
    id: 19,
    name: 'Pip',
    pet_type: 'Guinea Pig',
    age: 2,
    breed: 'American',
    sex: 'Male',
    coloration: 'Brown, Black, and White',
    weight: 2.5,
    is_sterilized: 'Yes',
    description:
      "Pip is a talkative and friendly guinea pig. He 'wheeks' with excitement whenever he hears the rustle of a veggie bag. He is easy to handle and would be a great first pet for a gentle child with adult supervision.",
    date_created: '2025-06-30T10:00:00Z',
    images: [],
  },
  {
    id: 20,
    name: 'Bella',
    pet_type: 'Dog',
    age: 9,
    breed: 'Shih Tzu',
    sex: 'Female',
    coloration: 'White and Gold',
    weight: 14,
    is_sterilized: 'Yes',
    description:
      "Bella is a sweet senior lady looking for a loving lap to retire on. She is calm, affectionate, and requires minimal exercise. She has some vision loss but navigates her space well once she's comfortable.",
    date_created: '2025-02-28T14:15:00Z',
    images: [],
  },
  {
    id: 21,
    name: 'Oreo',
    pet_type: 'Cat',
    age: 8,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'Black and White',
    weight: 10,
    is_sterilized: 'Yes',
    description:
      "Oreo is a classic beauty with a personality to match. She's an affectionate and playful senior who still loves to chase a string toy. She gets along with everyone and would make a wonderful family cat.",
    date_created: '2024-11-20T12:00:00Z',
    images: [],
  },
  {
    id: 22,
    name: 'Koda',
    pet_type: 'Dog',
    age: 2,
    breed: 'Siberian Husky',
    sex: 'Male',
    coloration: 'Black and White with Blue Eyes',
    weight: 55,
    is_sterilized: 'Yes',
    description:
      "Koda is a stunning husky with a mischievous and playful spirit. He needs a very active owner and a securely fenced yard. He is very talkative and will entertain you with his howls and 'woos'.",
    date_created: '2025-05-28T16:45:00Z',
    images: [],
  },
  {
    id: 23,
    name: 'Mittens',
    pet_type: 'Cat',
    age: 10,
    breed: 'Tabby',
    sex: 'Female',
    coloration: 'Brown Tabby with White Paws',
    weight: 9,
    is_sterilized: 'Yes',
    description:
      'Mittens is a sweet, gentle senior cat looking for a quiet home. She loves soft blankets, warm laps, and gentle pets. She is the perfect companion for someone looking for a low-key, loving friend.',
    date_created: '2025-01-15T15:30:00Z',
    images: [],
  },
  {
    id: 24,
    name: 'Hamlet',
    pet_type: 'Hamster',
    age: 1,
    breed: 'Syrian',
    sex: 'Male',
    coloration: 'Golden',
    weight: 0.3,
    is_sterilized: 'No',
    description:
      "Hamlet is a nocturnal explorer who loves to run on his wheel and burrow in his bedding. He's a bit shy but can be tamed with patience and sunflower seeds. He needs a home with a large, secure cage.",
    date_created: '2025-07-01T11:00:00Z',
    images: [],
  },
  {
    id: 25,
    name: 'Penny',
    pet_type: 'Dog',
    age: 4,
    breed: 'Corgi',
    sex: 'Female',
    coloration: 'Red and White',
    weight: 28,
    is_sterilized: 'Yes',
    description:
      'Penny is a confident and clever Corgi with a big smile. She is full of personality and loves to be involved in everything her family does. She is house-trained and gets along well with other dogs.',
    date_created: '2025-04-05T12:30:00Z',
    images: [],
  },
];
